spring:
  mvc:
    view:
      prefix: /WEB-INF/
  thymeleaf:
    enabled: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:jalal
  resources:
    static-locations: /src/main/resources/static/
